apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: default # Opcional: cámbialo si usas otro namespace
  annotations:
    argocd.argoproj.io/sync-wave: "20"
data:
  db_host: "postgres"
  db_port: "5432"
  db_name: "produccion_db"
  db_user: "admin"
